"""insert events

Revision ID: 197019734697
Revises: 5821129c9497
Create Date: 2025-04-29 23:09:33.268349

"""
from alembic import op
import sqlalchemy as sa
import json
import os
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '197019734697'
down_revision = '5821129c9497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # events 테이블 정의
    events_table = table('events',
        column('id', sa.Integer),
        column('title', sa.String),
        column('organizer', sa.String),
        column('month', sa.Integer),
        column('registration_period', sa.String),
        column('link', sa.String),
        column('category_json', sa.Text)
    )
    
    # json 파일 경로
    current_dir = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(current_dir, '..', 'resource', 'events.json')
    
    # json 파일 읽기
    with open(json_path, 'r', encoding='utf-8') as f:
        events_data = json.load(f)
    
    # 데이터 삽입
    for event in events_data:
        # category_json을 문자열로 변환
        if isinstance(event['category_json'], list):
            event['category_json'] = json.dumps(event['category_json'], ensure_ascii=False)
        
        op.bulk_insert(
            events_table,
            [
                {
                    'title': event['title'],
                    'organizer': event['organizer'],
                    'month': event['month'],
                    'registration_period': event['registration_period'],
                    'link': event['link'],
                    'category_json': event['category_json']
                }
            ]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM events')
    # ### end Alembic commands ### 